ao tentar rodar o teste no user_spec.rb, está apresentando o seguinte erro: bundle exec rspec spec/models/user_spec.rb FF
Failures:

  1) User is invalid if the level is not between 1 and 99
     Failure/Error: user = build(:user, level: FFaker::Random.rand(1..99))

     NoMethodError:
       undefined method `build' for #<RSpec::ExampleGroups::User "is invalid if the level is not between 1 and 99" (./spec/models/user_spec.rb:4)>
     # ./spec/models/user_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) User returns the correct hero title
     Failure/Error: user = create(:user, nickname: nickname, kind: kind, level: level)

     NoMethodError:
       undefined method `create' for #<RSpec::ExampleGroups::User "returns the correct hero title" (./spec/models/user_spec.rb:10)>
     # ./spec/models/user_spec.rb:15:in `block (2 levels) in <top (required)>'

Finished in 0.07531 seconds (files took 3.3 seconds to load)
2 examples, 2 failures

Failed examples:

rspec ./spec/models/user_spec.rb:4 # User is invalid if the level is not between 1 and 99
rspec ./spec/models/user_spec.rb:10 # User returns the correct hero title